In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

train=pd.read_csv("train_bsd.csv")
test=pd.read_csv("test_bsd.csv")

print(train.shape)
print(test.shape)

datasets=[train,test]

(10886, 12)
(6493, 9)

In [2]:
submit=pd.read_csv("sampleSubmission.csv")
print(submit.shape)
submit.head()

(6493, 2)

              datetime  count
0  2011-01-20 00:00:00      0
1  2011-01-20 01:00:00      0
2  2011-01-20 02:00:00      0
3  2011-01-20 03:00:00      0
4  2011-01-20 04:00:00      0

In [3]:
for dataset in datasets:
    dataset["datetime"]=pd.to_datetime(dataset["datetime"])

In [4]:
for dataset in datasets:
    dataset["datetime-year"]=dataset["datetime"].dt.year
    dataset["datetime-month"]=dataset["datetime"].dt.month
    dataset["datetime-hour"]=dataset["datetime"].dt.hour

In [6]:
for dataset in datasets:
    dataset["datetime-dayofweek"]=dataset["datetime"].dt.day_name()
    dataset[["datetime-dayofweek"]]

In [7]:
for dataset in datasets:
    dataset["datetime-dayofweek_Sun"]=dataset["datetime-dayofweek"]=="Sunday"
    dataset["datetime-dayofweek_Mon"]=dataset["datetime-dayofweek"]=="Monday"
    dataset["datetime-dayofweek_Tue"]=dataset["datetime-dayofweek"]=="Tuesday"
    dataset["datetime-dayofweek_Wed"]=dataset["datetime-dayofweek"]=="Wednesday"
    dataset["datetime-dayofweek_Thu"]=dataset["datetime-dayofweek"]=="Thursday"
    dataset["datetime-dayofweek_Fri"]=dataset["datetime-dayofweek"]=="Friday"
    dataset["datetime-dayofweek_Sat"]=dataset["datetime-dayofweek"]=="Saturday"

In [8]:
train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,...,datetime-month,datetime-hour,datetime-dayofweek,datetime-dayofweek_Sun,datetime-dayofweek_Mon,datetime-dayofweek_Tue,datetime-dayofweek_Wed,datetime-dayofweek_Thu,datetime-dayofweek_Fri,datetime-dayofweek_Sat
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,...,1,0,Saturday,False,False,False,False,False,False,True
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,...,1,1,Saturday,False,False,False,False,False,False,True
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,...,1,2,Saturday,False,False,False,False,False,False,True
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,...,1,3,Saturday,False,False,False,False,False,False,True
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,...,1,4,Saturday,False,False,False,False,False,False,True

In [9]:
test.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,datetime-year,datetime-month,datetime-hour,datetime-dayofweek,datetime-dayofweek_Sun,datetime-dayofweek_Mon,datetime-dayofweek_Tue,datetime-dayofweek_Wed,datetime-dayofweek_Thu,datetime-dayofweek_Fri,datetime-dayofweek_Sat
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027,2011,1,0,Thursday,False,False,False,False,True,False,False
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,1,Thursday,False,False,False,False,True,False,False
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,2,Thursday,False,False,False,False,True,False,False
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,3,Thursday,False,False,False,False,True,False,False
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,4,Thursday,False,False,False,False,True,False,False

# variables & model algorithm

In [10]:
feature_names=["season","holiday","workingday","weather","temp","atemp","humidity","windspeed","datetime-year","datetime-month","datetime-hour","datetime-dayofweek_Sun","datetime-dayofweek_Mon","datetime-dayofweek_Tue","datetime-dayofweek_Wed","datetime-dayofweek_Thu","datetime-dayofweek_Fri","datetime-dayofweek_Sat"]
feature_names

['season',
 'holiday',
 'workingday',
 'weather',
 'temp',
 'atemp',
 'humidity',
 'windspeed',
 'datetime-year',
 'datetime-month',
 'datetime-hour',
 'datetime-dayofweek_Sun',
 'datetime-dayofweek_Mon',
 'datetime-dayofweek_Tue',
 'datetime-dayofweek_Wed',
 'datetime-dayofweek_Thu',
 'datetime-dayofweek_Fri',
 'datetime-dayofweek_Sat']

In [11]:
x=train[feature_names]
y=train["count"]
x_test=test[feature_names]

In [12]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(random_state=37)
model

RandomForestRegressor(random_state=37)

# fit, predict & submit

In [13]:
model.fit(x,y)

RandomForestRegressor(random_state=37)

In [14]:
predlist=model.predict(x_test)
predlist

array([  9.85,   5.21,   3.83, ..., 141.5 , 110.74,  61.66])

In [15]:
submit["count"]=predlist
submit

                 datetime   count
0     2011-01-20 00:00:00    9.85
1     2011-01-20 01:00:00    5.21
2     2011-01-20 02:00:00    3.83
3     2011-01-20 03:00:00    3.53
4     2011-01-20 04:00:00    3.06
...                   ...     ...
6488  2012-12-31 19:00:00  288.65
6489  2012-12-31 20:00:00  193.57
6490  2012-12-31 21:00:00  141.50
6491  2012-12-31 22:00:00  110.74
6492  2012-12-31 23:00:00   61.66

[6493 rows x 2 columns]

In [16]:
submit.to_csv("randfore.csv",index=False)